// modules/clients.js
// ─── SEO client configs — edit client data here, not in server.js ─────────────
'use strict';

const CENTRAL_FL_CITIES = [
  'Orlando', 'Kissimmee', 'Winter Park', 'Winter Garden', 'Sanford',
  'Lake Mary', 'Celebration', 'Windermere', 'Clermont', 'Apopka',
  'Oviedo', 'Longwood', 'Altamonte Springs', 'Casselberry', 'Maitland',
  'St. Cloud', 'Lake Nona', 'Dr. Phillips', 'Narcoossee', 'Hunters Creek',
  'Deltona', 'Daytona Beach', 'Deland', 'Ocala', 'Leesburg',
  'Osceola County', 'Orange County', 'Seminole County', 'Lake County', 'Polk County',
];

function getTodaysCity() {
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0)) / 86400000);
  return CENTRAL_FL_CITIES[dayOfYear % CENTRAL_FL_CITIES.length];
}

// Add clients here to run daily blogs + weekly SEO plan for them.
// blogEnabled: false → skips daily blog but keeps GBP posts + all other automation
const SEO_CLIENTS = {
  'iipUT8kmVxJZzGBzvkZm': {
    name: 'Railing Max',
    domain: 'railingmax.com',
    lang: 'en',
    blogEnabled: false,
    gbpEnabled: false,
    industry: 'floating stairs, railing, and glass installation',
    competitors: ['viewrail.com', 'agsstainless.com', 'stairsupplies.com'],
    author: {
      name: 'Carlos Mendoza',
      title: 'Master Fabricator & Founder, Railing Max',
      credentials: 'Licensed structural fabricator with 12+ years installing floating stairs, glass railings, and custom metalwork across Florida. OSHA certified. 500+ residential and commercial installations completed statewide.',
      bio: 'Carlos founded Railing Max after spending a decade as a lead fabricator on luxury homes across Central Florida. He personally oversees every project — from the first consultation to the final inspection — because he knows that a floating staircase is the centerpiece of a home.',
    },
    voice: 'Expert craftsman and the go-to specialist for floating stairs in Florida. Knows every material, every code, every detail. Talks like someone who has built hundreds of custom staircases and railings — confident, specific, and zero fluff. When homeowners want floating stairs done right, this is who they call.',
    audience: 'Homeowners, architects, interior designers, and builders in Central Florida who want floating stairs, glass railings, cable railings, iron railings, or custom staircases. They care about the wow factor AND safety AND code compliance. They have seen floating stairs on Instagram and want that for their home.',
    keywords: [
      'floating stairs', 'floating stairs Orlando', 'floating stairs Florida',
      'floating staircase Orlando', 'floating staircase Florida', 'floating stairs near me',
      'open riser stairs Florida', 'open riser staircase Orlando',
      'glass railing Orlando', 'glass railing installation Florida',
      'stair railing contractor Orlando', 'railing installation Orlando',
      'cable railing Florida', 'cable railing Orlando',
      'iron railing Orlando', 'aluminum railing Florida',
      'pool fence Orlando', 'pool fence Clermont FL',
      'railing contractor Central Florida',
    ],
    topics: [
      'what are floating stairs and why every Orlando home wants them in 2026',
      'floating stairs cost guide Florida — what to expect before you build',
      'floating stairs vs traditional staircase which is right for your home',
      'how floating stairs are built — materials, codes, and installation process Florida',
      'best wood choices for floating stairs in Florida humidity',
      'floating stairs with glass railing the most popular combo in Orlando right now',
      'open riser staircase building codes Florida what you need to know',
      'how to get floating stairs installed in your Florida home step by step',
      'glass railing installation Orlando — cost, materials, and what to expect',
      'cable railing vs glass railing which looks better in a Florida home',
      'pool fence requirements Orange County Florida 2026',
      'stair railing contractor Orlando how to choose the right one',
      'iron railing vs aluminum railing which holds up better in Florida weather',
      'railing installation cost guide Central Florida',
      'custom railing ideas for Florida homes that stand out',
    ],
    cta: 'Get your free floating stairs or railing quote at railingmax.com',
    ga4PropertyId: '529233384',
    apiKey: 'pit-3a6936c1-5f10-4e4d-bb26-26bec9ebef1c',
    brand: {
      primary: '#d30400', accent: '#d30400', bg: '#ffffff', black: '#0a0a0a',
      grayMid: '#555', grayLight: '#f5f5f5',
      fontDisplay: 'Bebas Neue', fontBody: 'Manrope',
      fontImport: 'https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Manrope:wght@300;400;500;600;700;800&display=swap',
      logoUrl: 'https://assets.cdn.filesafe.space/iipUT8kmVxJZzGBzvkZm/media/69b80afa87f2fb2848a34872.png',
      stats: ['500+ Projects', '10+ Years Experience', 'All of Florida', '100% Satisfaction'],
      trustBadges: ['Licensed & Insured', 'Free Consultations', '24/7 Support', 'Statewide Install'],
      phone: '(407) 412-5421',
    },
  },
  'rJKRuyayc6Z6twr9X20v': {
    name: 'The Escobar Kitchen',
    domain: 'theescobarkitchen.com',
    lang: 'en',
    industry: 'Latin Asian fusion restaurant',
    blogEnabled: true,
    gbpEnabled: true,
    weekdayOnly: true, // Mon–Fri blogs only
    competitors: ['thepressorlando.com', 'christners.com', 'orlandofoodcritic.com'],
    author: {
      name: 'Chef Andres Escobar',
      title: 'Executive Chef & Co-Owner, The Escobar Kitchen',
      credentials: 'Culinary-trained chef with 15+ years crafting Latin-Asian fusion cuisine. Co-creator of The Escobar Kitchen\'s signature menu. Opened 3 locations across Central Florida.',
      bio: 'Chef Andres built The Escobar Kitchen around one idea: what happens when Latin soul meets Asian precision. Every dish on the menu started in his home kitchen — tested, tasted, and refined until it was something genuinely worth driving across town for.',
    },
    voice: 'Bold, passionate, and proud of every single dish. Writes like someone who is genuinely obsessed with food — the flavors, the craft, the experience. Warm but confident. Makes you feel like you are missing out if you are not there tonight.',
    audience: 'Food lovers in Hunters Creek, Lake Nona, Downtown Orlando, and greater Central Florida searching for something beyond the ordinary — a restaurant where Latin soul meets Asian precision. Date nights, celebrations, foodies, and anyone who searches "best sushi near me" or "latin restaurant near me".',
    keywords: [
      // Brand + location
      'escobar kitchen orlando', 'escobar kitchen hunters creek', 'escobar kitchen lake nona', 'escobar kitchen downtown orlando',
      // Sushi + fusion
      'best sushi orlando', 'sushi hunters creek orlando', 'sushi lake nona orlando', 'sushi downtown orlando',
      'latin asian fusion orlando', 'latin asian fusion near me', 'asian fusion orlando',
      // Restaurant type
      'latin restaurant orlando', 'latin restaurant near me', 'latin restaurant hunters creek', 'latin restaurant lake nona',
      'fusion restaurant central florida', 'unique restaurants orlando',
      // Dishes
      'crispy rice orlando', 'spicy tuna crispy rice orlando', 'empanadas orlando', 'latin bowls orlando', 'fusion tacos orlando',
      // Occasion
      'date night restaurants orlando', 'date night downtown orlando', 'wine bar downtown orlando',
      'best romantic restaurants orlando', 'birthday dinner orlando',
      // Catering
      'latin catering orlando', 'catering orlando latin food', 'corporate catering orlando',
      // Order intent
      'order sushi online orlando', 'order latin food orlando', 'best latin food orlando',
    ],
    topics: [
      // Brand authority
      'why The Escobar Kitchen is the best latin asian fusion restaurant in Central Florida',
      'what to order at The Escobar Kitchen — a locals complete guide',
      'the story behind The Escobar Kitchen and how it became an Orlando favorite',
      // Location-specific
      'best restaurants in hunters creek orlando — why escobar kitchen tops the list',
      'lake nona restaurant guide — the hidden gem inside The Bravo Market',
      'best sushi in downtown orlando — escobar kitchen on church street',
      'hunters creek food scene — why escobar kitchen is the neighborhood favorite',
      'lake nona dining — what makes escobar kitchen different from every other restaurant',
      'wine bar and sushi downtown orlando — escobar kitchen date night guide',
      // Dish-specific
      'what is crispy rice tuna and why its the most talked-about dish in orlando',
      'shrimp empanadas orlando — why escobar kitchens are in a category of their own',
      'latin bowls orlando — the healthy bold fusion dish you need to try',
      'fusion tacos at escobar kitchen — east meets west on one plate',
      'best empanadas near me orlando — a locals honest guide',
      // Catering
      'catering for corporate events in orlando — why escobar kitchen fusion food wins every time',
      'birthday party catering ideas orlando — latin asian fusion platters that wow',
      'wedding catering orlando latin food options your guests will never forget',
      // Occasion + seasonal
      'best date night restaurants orlando 2026 — top picks for a memorable night out',
      'valentines day dinner orlando 2026 — romantic restaurant ideas',
      'mothers day brunch ideas orlando — latin food that makes it special',
      'best restaurants for a celebration orlando — from birthdays to anniversaries',
      // Order intent + value
      'why you should order direct instead of doordash or uber eats in orlando',
      'how to save money ordering food in orlando — skip the app fees',
      'best latin food delivery orlando — order direct from escobar kitchen',
      // SEO wide net
      'best sushi near disney world orlando',
      'asian fusion vs traditional sushi — what makes escobar kitchen unique',
      'latin restaurant narcoossee fl — hidden gem worth the drive',
      'upscale casual dining lake nona orlando 2026',
      'top orlando restaurants locals actually love in 2026',
    ],
    cta: 'Order direct at theescobarkitchen.com/locations — no app fees, pickup in 15 minutes',
    ctaUrl: 'https://theescobarkitchen.com/locations',
    locationPages: {
      'Hunters Creek': 'https://theescobarkitchen.com/hunters-creek',
      'Lake Nona': 'https://theescobarkitchen.com/lake-nona',
      'Downtown Orlando': 'https://theescobarkitchen.com/downtown-orlando',
    },
    ga4PropertyId: '529262280',
    apiKey: 'pit-5d229b3d-b6ad-4c81-9935-69076152ea1a',
    brand: {
      plainHtml: true,
      logoUrl: 'https://assets.cdn.filesafe.space/rJKRuyayc6Z6twr9X20v/media/69a7ac1bb701fe6a3e793b91.png',
      mediaImages: [
        'https://assets.cdn.filesafe.space/rJKRuyayc6Z6twr9X20v/media/699b3b45df9bdf880b05c99c.jpg',
        'https://assets.cdn.filesafe.space/rJKRuyayc6Z6twr9X20v/media/699b3b45df9bdf54b605c975.jpg',
        'https://assets.cdn.filesafe.space/rJKRuyayc6Z6twr9X20v/media/699b3b44df9bdfd6d905c970.jpg',
        'https://assets.cdn.filesafe.space/rJKRuyayc6Z6twr9X20v/media/699b3b44df9bdf4a3705c944.jpg',
        'https://assets.cdn.filesafe.space/rJKRuyayc6Z6twr9X20v/media/699b3b45df9bdf8ef905c98e.jpg',
        'https://assets.cdn.filesafe.space/rJKRuyayc6Z6twr9X20v/media/699b3b44df9bdf2d8c05c96c.jpg',
        'https://assets.cdn.filesafe.space/rJKRuyayc6Z6twr9X20v/media/699b3b44df9bdf08bc05c940.jpg',
        'https://assets.cdn.filesafe.space/rJKRuyayc6Z6twr9X20v/media/699b3b454c8da2997996c53d.jpg',
        'https://assets.cdn.filesafe.space/rJKRuyayc6Z6twr9X20v/media/699b3b4455d8bc7efa4455ea.jpg',
      ],
      stats: ['4.6★ Google', '452+ Reviews', '3 Locations', 'Catering Available'],
      trustBadges: ['Order Direct & Save', 'Latin-Asian Fusion', 'Dine-In & Delivery', 'Family Friendly'],
      phone: '',
    },
  },
  '6FdG0APBuZ81P8X2H4zc': {
    name: 'Rental Spaces',
    domain: 'rentalspacesinc.com',
    lang: 'en',
    industry: 'RV and boat storage',
    competitors: ['rvshare.com', 'storagemart.com', 'extraspace.com'],
    author: {
      name: 'David Torres',
      title: 'Founder & Storage Specialist, Rental Spaces',
      credentials: '10+ years providing secure RV, boat, and vehicle storage in Central Florida. Expert in outdoor storage solutions for Florida\'s climate, HOA regulations, and seasonal storage needs.',
      bio: 'David started Rental Spaces after realizing how few options RV and boat owners in Orlando had for secure, affordable storage. He built the facility with the kind of security and access he\'d want for his own equipment.',
    },
    voice: 'Practical and no-nonsense. Speaks to people who love their toys (RVs, boats, ATVs) and want safe, affordable storage without the hassle. Friendly but to the point.',
    audience: 'RV owners, boaters, and outdoor enthusiasts in the Orlando area who need secure, affordable storage between trips.',
    topics: ['how to store your RV in Florida summer', 'boat storage near Orlando', 'indoor vs outdoor RV storage', 'tips for winterizing your boat in Florida', 'how to choose an RV storage facility', 'cost of boat storage Orlando', 'RV storage security features to look for'],
    cta: 'Reserve your storage space at rentalspacesinc.com',
    keywords: ['RV storage Orlando', 'boat storage Orlando', 'covered RV storage Florida', 'outdoor boat storage Central Florida', 'climate controlled RV storage Orlando', 'monthly boat storage Kissimmee', 'secure RV storage Florida', 'RV parking near Orlando', 'self storage for boats Florida'],
    blogEnabled: false,
    apiKey: 'pit-1b29023e-d415-4ab6-b18d-1a1072d4c355',
    brand: { primary: '#080808', accent: '#116dff', bg: '#ffffff', logoUrl: '' },
  },
  'Emg5M7GZE7XmnHc7F5vy': {
    name: 'Guaca-Mole-Tex-Mex',
    domain: 'guaca-mole-texmex.com',
    lang: 'en',
    industry: 'Tex-Mex restaurant',
    competitors: ['chuy.com', 'ontheborder.com', 'orlandofoodcritic.com'],
    author: {
      name: 'Roberto Martinez',
      title: 'Head Chef & Owner, Guaca-Mole Tex-Mex',
      credentials: 'Tex-Mex specialist with 12+ years cooking in Orlando. Family recipes brought from South Texas, adapted with fresh Florida ingredients. Known for the best from-scratch guacamole in Central Florida.',
      bio: 'Roberto opened Guaca-Mole because he was tired of chain Tex-Mex that tasted like nothing. Everything here is made from scratch daily — the salsas, the guac, the tortillas. If his abuela wouldn\'t approve, it doesn\'t make the menu.',
    },
    voice: 'Fun, bold, and unapologetically Tex-Mex. Celebrates big flavors, good times, and authentic recipes. Casual, energetic, and makes you hungry just reading it.',
    audience: 'Families, friend groups, and Tex-Mex lovers in Orlando looking for generous portions, great margaritas, and a lively atmosphere.',
    topics: ['best Tex-Mex in Orlando', 'authentic guacamole made fresh daily', 'best margaritas Orlando FL', 'Tex-Mex vs Mexican food what is the difference', 'family-friendly restaurants Orlando', 'best tacos near me Orlando', 'happy hour deals Orlando restaurants'],
    cta: 'Come hungry — find us at guaca-mole-texmex.com',
    keywords: ['tex mex restaurant Orlando', 'best tacos Orlando', 'mexican restaurant near me Orlando', 'authentic mexican food Central Florida', 'best margaritas Orlando', 'guacamole restaurant Orlando', 'family tex mex Kissimmee', 'best burritos Orlando', 'happy hour tex mex Orlando'],
    blogEnabled: false,
    apiKey: 'pit-3ba32a5e-775f-46e6-9e5d-4a201148f7fb',
  },
  'd7iUPfamAaPlSBNj6IhT': {
    name: 'JRZ Marketing',
    domain: 'jrzmarketing.com',
    lang: 'en',
    industry: 'AI marketing agency',
    competitors: ['webfx.com', 'thehoth.com', 'ignitevisibility.com'],
    author: {
      name: 'José Rivas',
      title: 'Founder & AI Marketing Strategist, JRZ Marketing',
      credentials: 'Digital marketing strategist specializing in AI automation, Go High Level systems, and local SEO for small businesses. Built fully automated marketing systems managing 30+ client accounts across Florida.',
      bio: 'José founded JRZ Marketing after watching too many small businesses get burned by agencies that overpromised and underdelivered. He built his own AI-powered system from scratch — one that runs 24/7, captures leads while clients sleep, and actually moves the needle on local rankings.',
    },
    voice: 'Sharp, confident, and results-driven. José Rivas speaks from real experience building systems that work. Bilingual edge, deep understanding of Latino entrepreneurs, zero tolerance for fluff or wasted ad spend.',
    audience: 'Small business owners, Latino entrepreneurs, and service-based businesses in Orlando and Central Florida who want real growth — more leads, more sales, more automation.',
    topics: ['AI marketing automation for small business Orlando', 'how to get more leads without spending more on ads', 'Go High Level for small business', 'social media automation that actually works', 'bilingual marketing strategy Florida', 'how to rank your business on Google Maps Orlando', 'marketing mistakes small business owners make'],
    cta: 'Book your free strategy call at jrzmarketing.com/contact-us',
    keywords: ['marketing agency Orlando', 'social media marketing Orlando', 'digital marketing Florida', 'GoHighLevel agency Orlando', 'local SEO Orlando', 'lead generation Orlando', 'marketing automation small business', 'AI marketing automation Florida', 'bilingual marketing agency Orlando'],
    ga4PropertyId: '384751711',
    apiKey: 'pit-9d4919d5-9d6e-4aa9-8c01-e9c1985a3e2e',
    brand: { primary: '#212322', accent: '#37ca37', bg: '#ffffff', logoUrl: 'https://assets.cdn.filesafe.space/d7iUPfamAaPlSBNj6IhT/media/6957072d035c3a047c37bf66.png' },
  },
  'Gc4sUcLiRI2edddJ5Lfl': {
    name: 'Cooney Homes',
    domain: 'cooneyhomesfl.com',
    lang: 'en',
    industry: 'general contractor — home additions, custom home building, and remodeling',
    competitors: ['buildwithbbt.com', 'myhomeus.com', 'semiholehomes.com'],
    author: {
      name: 'Mike Cooney',
      title: 'Licensed General Contractor & Founder, Cooney Homes',
      credentials: 'Florida-licensed General Contractor (CGC licensed), 18+ years building custom homes and additions across Orange, Osceola, Polk, and Hillsborough counties. Member of the Home Builders Association of Metro Orlando.',
      bio: 'Mike started Cooney Homes because he saw too many homeowners get burned by contractors who disappeared mid-project or cut corners on permits. Every Cooney Homes build is owner-led — Mike is on-site, reachable, and accountable from groundbreak to final walkthrough.',
    },
    voice: 'Experienced builder who has seen every type of project in Florida and knows exactly what it takes to do it right. Practical, confident, and zero tolerance for shortcuts. Speaks to homeowners who want their vision built properly — on time and on budget.',
    audience: 'Florida homeowners who want to add square footage, build a custom home from scratch, add a garage, expand a kitchen, or build an in-law suite. Also builders and developers in Central Florida looking for a trusted general contractor.',
    keywords: [
      'general contractor Orlando', 'home addition Orlando', 'custom home builder Orlando',
      'room addition Central Florida', 'home remodel Orlando', 'kitchen addition Florida',
      'in-law suite addition Orlando', 'garage addition Florida', 'custom home construction Orlando',
      'home expansion contractor Central Florida',
    ],
    topics: [
      'how much does a home addition cost in Florida 2026',
      'custom home builder vs production builder which is right for you',
      'home addition ideas that add the most value in Central Florida',
      'how to add a room to your house in Florida step by step',
      'building an in-law suite in Orlando what you need to know',
      'kitchen addition vs full remodel which makes more sense',
      'garage addition costs and permits in Orange County Florida',
      'how to find a trustworthy general contractor in Central Florida',
      'how long does a home addition take in Florida',
      'building a custom home in Orlando from land to move-in',
    ],
    cta: 'Start your project with a free consultation at cooneyhomesfl.com',
    ga4PropertyId: '503054433',
    apiKey: 'pit-cd43cc72-9e18-4eee-9bfb-be5942de9722',
    brand: {
      primary: '#f9bf4d', accent: '#f47d72', bg: '#ffffff', ctaBg: '#121212',
      textColor: '#121212', bodyColor: 'rgba(18,18,18,0.70)',
      fontDisplay: 'Poppins', fontBody: 'Poppins',
      fontImport: 'https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700;800;900&display=swap',
      logoUrl: 'https://storage.googleapis.com/msgsndr/Gc4sUcLiRI2edddJ5Lfl/media/69861a783fae0a0ae13022b8.png',
      stats: ['Clean Communication', 'High Craftsmanship', 'Strong Project Control', 'Built for Value'],
      trustBadges: ['Licensed General Contractor', 'Owner-Led Builds', 'Free Consultations', 'Central Florida'],
      phone: '(407) 201-4100',
    },
  },
  'OpdBPAp31zItOc5IIykL': {
    name: 'Le Varon Barbershop',
    domain: 'levaronbarbershop.com',
    lang: 'en',
    industry: 'barbershop',
    author: {
      name: 'Luis Varón',
      title: 'Master Barber & Owner, Le Varón Barbershop',
      credentials: 'Florida-licensed master barber with 10+ years specializing in precision fades, tapers, and beard sculpting. Built Le Varón from a single chair into one of Orlando\'s most respected barbershops.',
      bio: 'Luis opened Le Varón because he believed Orlando deserved a barbershop that took the craft seriously. Not just a haircut — a whole experience. He trains every barber on his team personally and still takes clients himself every week.',
    },
    voice: 'Cool, confident, and community-rooted. Celebrates the culture of the barbershop — where men come for more than a haircut. Speaks the language of style, brotherhood, and taking pride in your appearance.',
    audience: 'Men in Orlando who care about their look — from clean fades to beard lineups. Loyal barbershop clients who see their barber as part of their weekly routine.',
    topics: ['best barbershop Orlando FL', 'how to find the right barber', 'fade haircut styles 2026', 'how to maintain your beard between cuts', 'barbershop vs hair salon what is the difference', 'mens grooming tips Orlando', 'why a good barber is worth it'],
    cta: 'Book your appointment at levaronbarbershop.com',
    keywords: ['barbershop Orlando', 'best barbershop near me', 'mens haircut Orlando', 'fade haircut Orlando', 'barbershop Kissimmee', 'mens grooming Orlando', 'beard trim Orlando', 'Latino barbershop Central Florida', 'fresh cut near me Orlando'],
    blogEnabled: false,
  },
  'VWHZW08b0skUV7wcnG55': {
    name: 'USA Latino CPA',
    domain: 'usalatinocpa.com',
    lang: 'en',
    industry: 'accounting and tax services',
    voice: 'Trustworthy, clear, and culturally aware. Speaks to Latino business owners and immigrants who have been underserved by mainstream accountants. Demystifies taxes and finances without being condescending — in plain language, sometimes with Spanish terms.',
    audience: 'Latino entrepreneurs, self-employed immigrants, and small business owners in Florida who need bilingual accounting help, tax filing, and financial guidance they can actually understand.',
    topics: ['how to file taxes as a self-employed immigrant Florida', 'LLC vs sole proprietor for Latino business owners', 'tax deductions for small business owners', 'how to build business credit in the US', 'ITIN taxes what you need to know', 'accounting tips for restaurant owners', 'why your business needs a bilingual CPA'],
    cta: 'Schedule a free consultation at usalatinocpa.com',
    keywords: ['CPA Orlando', 'accountant Orlando', 'tax preparation Orlando', 'small business accounting Orlando', 'bookkeeping services Orlando', 'business tax return Florida', 'bilingual accountant Orlando', 'tax planning small business Florida', 'CFO services small business Orlando'],
    apiKey: 'pit-525c7ac9-a267-4e71-a26b-a43f12d27079',
    ga4PropertyId: '529255116',
    brand: {
      primary: '#073353', accent: '#e32133', bg: '#ffffff', ctaBg: '#073353',
      textColor: '#073353', bodyColor: '#5c6b78',
      fontDisplay: 'Montserrat', fontBody: 'Montserrat',
      fontImport: 'https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&display=swap',
      logoUrl: 'https://storage.googleapis.com/msgsndr/VWHZW08b0skUV7wcnG55/media/6980282f66e7ca4a74ce0924.png',
      stats: ['5.0★ Google', 'CPA-Level Accuracy', 'Proactive Planning', 'Bilingual EN/ES'],
      trustBadges: ['Proactive Tax Planning', 'Pristine Books', 'IRS-Ready Compliance', 'Bilingual Service'],
      phone: '(689) 233-7398',
    },
  },
  // Add more clients below — copy the format above
  // 'LOCATION_ID': { name, domain, lang, industry, voice, audience, topics: [], cta },
};

module.exports = { CENTRAL_FL_CITIES, getTodaysCity, SEO_CLIENTS };
